name: "Release"
run-name: Publishing on "${{ github.ref }}" by "${{ github.actor }}"
on:
  release:
    type: released

jobs:
  # Run build
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --all-extras
      - run: uv run build
      - uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  # Run deploy
  deploy:
    needs:
      - build
    runs-on: ubuntu-22.04
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - run: uv sync --all-extras
      - run: uv publish --token $UV_PUBLISH_TOKEN
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "release: bump version and generate changelog"
